<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bulan</name>
   <tag></tag>
   <elementGuidId>6f38630c-9457-473b-9bd2-37f3c5af30be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab--tabs--1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tab--tabs--1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;expanded-searchbar-dates-months-tab&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae0d8175-4f04-402a-b2e2-9c7423bd200b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b1751fc-da21-4a7c-85fa-504332693b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab--tabs--1</value>
      <webElementGuid>0b389d76-9ab5-4d2d-8cc5-814ab703ecec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>panel--tabs--1</value>
      <webElementGuid>33bb370a-fce4-4e9b-9f60-0d0c82f3bbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6ad945c-8367-41de-a92f-da4b2ee90c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>expanded-searchbar-dates-months-tab</value>
      <webElementGuid>51207ed5-34f2-4ca9-a743-8e2d09b1fa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>taifrq6 atm_bx_48h72j atm_c8_km0zk7 atm_g3_18khvle atm_fr_1m9t47k atm_cs_10d11i2 atm_26_1j28jx2 atm_uc_1lizyuv atm_mk_h2mmj6 atm_kd_glywfm atm_5j_12xxubj atm_7l_dezgoh atm_l8_1fqechy atm_gi_tlkmqw atm_3f_okh77k atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_uc_aaiy6o_1w3cfyq atm_7l_jt7fhx_1w3cfyq atm_70_1e7pbig_1w3cfyq atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_uc_aaiy6o_pfnrn2_1oszvuo atm_7l_jt7fhx_pfnrn2_1oszvuo atm_70_1e7pbig_pfnrn2_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_tr_18md41p_csw3t1 atm_9j_13gfvf7_1o5j5ji atm_7l_9vytuy_1o5j5ji atm_26_1j28jx2_1mj13j2_uv4tnr atm_uc_glywfm__1rrf6b5 atm_gz_19lyhz2_13mkcot atm_h0_19lyhz2_8dt821 atm_26_1oqmvsg_1nos8r_uv4tnr atm_26_1oqmvsg_1w3cfyq atm_3f_n7od8j_1w3cfyq atm_26_1oqmvsg_pfnrn2_1oszvuo atm_3f_n7od8j_pfnrn2_1oszvuo atm_26_1j28jx2_1nos8r_qcp22u dir dir-ltr</value>
      <webElementGuid>d7a3aac0-b32c-4643-b8d8-d036993e6977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1784089c-0262-49fd-9f0a-62bcbd873486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a67a9420-f675-442d-8254-5e5128c00533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulan</value>
      <webElementGuid>f096e324-b38d-4c6d-9576-44831beba1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab--tabs--1&quot;)</value>
      <webElementGuid>7743dcd5-6653-4290-9a5f-79297d7e4241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tab--tabs--1']</value>
      <webElementGuid>3b02204b-8fe9-491a-9e85-47d656020738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/div/div/div/div/button[2]</value>
      <webElementGuid>5c34f2a0-df09-41bc-a916-535b0065bb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[1]/following::button[1]</value>
      <webElementGuid>7092c6bd-26e0-420f-a21d-bac7f7797ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambahkan tanggal'])[1]/following::button[2]</value>
      <webElementGuid>3f9e5596-c3be-4436-b3c9-87630f21b1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fleksibel'])[3]/preceding::button[1]</value>
      <webElementGuid>d9a98466-3b6a-440d-bb3b-347bd51fda74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Min'])[1]/preceding::button[2]</value>
      <webElementGuid>1007c065-b91b-401f-814a-80c68b5e96d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bulan']/parent::*</value>
      <webElementGuid>cc6b194b-a7e9-4e3f-948a-7e3b71534936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>f9aa70c0-5719-4c9a-817c-34fac8e659a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'tab--tabs--1' and (text() = 'Bulan' or . = 'Bulan')]</value>
      <webElementGuid>58c41238-77ce-45fc-a0cf-fa22edcdc3d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
